telicent-oss/telicent-ds

- package.json
Merging in manually with `-rc3` tag caused release-me-please to open release branch with `-rc3`
So for now I'll just manually remove - and for certainty, I did a manual bump.
This _should_ trigger an "xtra bump" to 0.0.4 - but is not ideal but is is harmless. And temporary
> bump(package.json)

- package.json
When importing the ds in to another app it was throwing an error, 'Could not find a declaration file'.
Although the type location was explicitly stated in the package.json file. The only way to get the error to disappear was to add the types path to the exports
> fix(package.json): update package.json

- package.json
- yarn.lock
Before
```
info Has been hoisted to "nth-check"
info Reasons this module exists
- Hoisted from "css-select#nth-check"
- Hoisted from "release-please#node-html-parser#css-select#nth-check"
info Disk size without dependencies: "120KB"
info Disk size with unique dependencies: "132KB"
info Disk size with transitive dependencies: "132KB"
info Number of shared dependencies: 1
=> Found "svgo#nth-check@1.0.2"
info Reasons this module exists
- "react-scripts#@svgr#webpack#@svgr#plugin-svgo#svgo#css-select" depends on it
- Hoisted from "react-scripts#@svgr#webpack#@svgr#plugin-svgo#svgo#css-select#nth-check"
info Disk size without dependencies: "24KB"
info Disk size with unique dependencies: "36KB"
info Disk size with transitive dependencies: "36KB"
info Number of shared dependencies: 1
✨  Done in …
```
> fix(vuln): [TELFE-336] nth-check

- .github/workflows/build-package.yml
- .github/workflows/check-build-cron.yml
- .github/workflows/publish.yml
The publish workflow is current failing because the publish step cannot find the build folder. This is because the build and publish steps are being executed in separate contexts.
To ensure the artefacts are available before the publish step, the build artefacts are stored after the build step if dry-run is set to false (it's set to false by default) and are retrieved before the publish step executed
[TELFE-73](https://telicent.atlassian.net/browse/TELFE-73)
[TELFE-73]: https://telicent.atlassian.net/browse/TELFE-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Setup build cron job - Publish workflow fix

- .github/workflows/publish.yml
Removed path from publish.yml to resolve error which was occuring when attempting to publish package. The error was occurring because the artefacts were being in the wrong directory. Now using the default workspace as the download directory
> Setup build cron job - Fix publish action

- .github/workflows/build-package.yml
- .github/workflows/publish.yml
Refactored the publish.yml workflow to contain all the required steps to make the workflow work in a similar way to how it was setup originally.
Resolved could not find package.json error from action by adding checkout repository step.
Moved across permission from build.yml to publish.yml as the permission are needed for publishing not building
> fix: publish workflow

- package.json
- yarn.lock
ontologyservice used a library that had a vulnerability
> fix: bump dependency versions

- package.json
- src/v1/components/data-display/Text/Text.test.tsx
An example showing:
- Minimal jest tests to get 100% test coverage. 
- Does not retest functionality in MUI.
- Biases toward renderFragment and inlineSnapshots (for ease of writing and 
maintenance)
> fix(v1 Text):added coverage

- src/v1/components/data-display/AppSwitch/AppSwitch.tsx
- src/v1/components/data-display/index.ts
- src/v1/components/surfaces/AppBar/AppBar.tsx
- src/v1/components/surfaces/index.ts
Exporting types so they can be imported in other applications
> fix: export appswitchlibrary and appbar types

- src/v1/components/data-display/FontAwesomeIcons/ClockIcon.tsx
- src/v1/components/data-display/FontAwesomeIcons/DownArrowIcon.tsx
- src/v1/components/data-display/FontAwesomeIcons/DownloadIcon.tsx
- src/v1/components/data-display/FontAwesomeIcons/SearchIcon.tsx
To get [this ticket ](https://telicent.atlassian.net/browse/TELFE-660) completed, the color prop is required in the font awesome icons to match designs in the ticket.
> fix: add color prop to font awesome icons

- package.json
- yarn.lock
Removed `cross-env` dev dependency as it wasn't being used. It has a dependency to an older version of `cross-spawn`.
Updated eslint to version 9, version 8 is no longer maintained. It has a dependency to an older version of `cross-spawn`
Added version 7.0.6 of `cross-spawn` into the resolutions field.
Will need to remove react-scripts at some point as it's no longer maintained. It still using an older version of `cross-spawn`.
> fix: security fixes

- src/v1/components/surfaces/index.ts
I didn't realise how all the components were being exported from specific files. Exported FixedPanel from `surfaces/index.ts`
> fix: export fixed panel from surfaces

- src/v1/components/data-display/UserProfile/UserProfileContent/UserProfileContent.tsx
fix: remove unused header on the user profile content to match current design
tested on Graph using yarn link
> Fix: User Profile Content

- src/v1/components/surfaces/AppBar/AppBar.stories.tsx
- src/v1/components/surfaces/AppBar/AppBar.test.tsx
- src/v1/components/surfaces/AppBar/AppBar.tsx
Updated the AppBar component to accept a startChild prop instead of having AppSwitch hardcoded. This change improves flexibility, allowing any component to be passed as the start section of the AppBar while maintaining the existing functionality.
> fix: app switch on app bar

- src/v1/components/surfaces/AppBar/AppBar.tsx
fix a small bug where version number would render on top of brand if it was too long.
> fix: version number rendering on top of brand if too long

- .github/workflows/test-feature-branch.yml
- package.json
See workflow: https://github.com/telicent-oss/shared-workflows/pull/100
Runs tsc --noEmit:
* [but doesn't kill job when flag true](https://github.com/telicent-oss/telicent-ds/actions/runs/13590663886/job/37995752502)
* [and kills job with flag false](https://github.com/telicent-oss/telicent-ds/actions/runs/13590701515/job/37995892439)
* [and kills job when flag doesn't exist](https://github.com/telicent-oss/telicent-ds/actions/runs/13590707497/job/37995912688)
Note: subsequent unit tests still fail job
Proof it works with main branch of shared-workflows
https://github.com/telicent-oss/telicent-ds/actions/runs/13590999965/job/37996884891
> Don't block if tsc --noEmit fails

- src/component-library/Map/map.css
Text inherits from the app, which in some cases means we get white text on a white background
> fix: make text black

- src/component-library/Map/FeatureMap.tsx
On search when I pan it keeps snapping back to bounds. This is because every paint the geoPolygons is a new object and forces a recalculation.
Small fix as part of https://telicent.atlassian.net/browse/TELFE-876
> fix: map snapping back to bounds

- src/component-library/Map/FeatureMap.tsx
Map wasn't panning when loading the single result. This wast becasue the data was not changing after the map had loaded like on the other page.
The useEffect that calculated the bounds would not be re-triggered when the map was finally ready because `ref`'s are not observed.
There is an `onLoad` prop which I have utilised instead.
> fix: use onLoad to ensure ref is loaded

- src/v1/components/inputs/SearchBox/MiniSearchAutocomplete.test.tsx
- src/v1/components/inputs/SearchBox/MiniSearchAutocomplete.tsx
https://telicent.atlassian.net/browse/TELFE-848
Added onKeyDown Prop so that Graph can implement a listener for when the user presses 'Enter'
Add a test to ensure that the callback gets triggered on keypress
> fix(MiniSearchAutocomplete): add onKeyDown prop

- src/v1/components/inputs/Button/Button.tsx
- src/v1/components/inputs/Button/LinkButton.tsx
- src/v1/components/inputs/Button/PrimaryButton.tsx
- src/v1/components/inputs/Button/SecondaryButton.tsx
Ticket: Done as part of [TELFE-569](https://telicent.atlassian.net/browse/TELFE-569)
The buttons in graph all use [MUI Tooltip](https://mui.com/material-ui/react-tooltip/?srsltid=AfmBOor1LmPjMRSnrvlItG2i9vcOEeNAbP3LUhVsyPHu7O_a296RuI70), which weren't working with the buttons provided by the DS. 
The goal is to make the tooltips work with Telicent themed buttons.
Add refs to all button variants.
I linked the DS to graph and manually tested.
No additional tests have been added for the tests.
---
<details>
---
- The aim of both PR …
> fix: add refs to all buttons

- src/v1/components/data-display/DropdownButton/DropdownButton.tsx
- src/v1/components/inputs/Button/Button.tsx
- src/v1/components/layout/FlexBox.tsx
Ticket: https://telicent.atlassian.net/browse/TELFE-269
Update button component to have an option for a un styled  button, and added forward ref to Flexbox. 
Fix typescript error on Dropdown Menu. 
`onClick={() => onClick(value)}`
---
<details>
---
2. [Review the code](https://google.github.io/eng-practices/review/reviewer/looking-for.html)
3. …
> fix: button and flexbox

- src/candidate-packages/utils-lib/src/Logger/Logger.test.ts
- src/candidate-packages/utils-lib/src/Logger/Logger.ts
- src/candidate-packages/utils-lib/src/index.ts
- src/export.ts
Ticket: in service of TELFE-1184
Our method for debug output is unclear - causing a few instances of missing output. 
Want:
```ts
// usage
const logger = new Logger();
logger.debug('pre-init debug');  // buffered
logger.info('pre-init info');    // buffered
// later...
logger.setLevel('debug');        // flushes only debug+ levels
logger.info('post-init');        // logs immediately
```
Simple solution
Log levels:
https://github.com/user-attachments/assets/1a7ab4ce-0bae-4ed2-b8b9-cd769a5eecf1
Queue if not inited, and Flush after init
https://github.com/user-attachments/assets/3d46874d-98d1-41fa-a878-647419a18f40
---
<details>
---
- Generally, approve a PR if it makes the system better, even if it's not perfect. — …
> feat(Logger): [TELFE-1184] added
