telicent-oss/telicent-ds

package.json

update(package.json): description

---

.github/workflows/publish.yml

ci: set npmrc token

---

.storybook/DocsContainer.tsx
.storybook/ThemeWrapper.tsx
.storybook/main.ts
.storybook/manager.ts
.storybook/preview-body.html
.storybook/preview.tsx
package.json

I needed this to run Storybook locally
https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092

update: needed to run

---

package.json
yarn.lock

- telicent-io chagned to telicent-oss
- (optimistic) tweaks to Readme

update closed refs to os refs

---

.github/workflows/upload-storybook.yml
README.md
yarn.lock

1. Won't see the hosted Storybook until https://github.com/Telicent-io/telicent-ds/issues/377
2. See my fork's hosted Storybook here: https://acoolmantelicent.github.io/telicent-ds/
3. There is a chance `Update storybook` doesn't work - Github status had warnings, and delayed deployment by 2hrs - so I don't know _for sure_ this version is what worked. But, even if the workflow is bugged - "Its an improvement".
* Requested fixes for https://github.com/Telicent-io/telicent-ds/issues/332
* IMPORTANT: Also fixes `yarn.lock` and will unblock  https://github.com/telicent-oss/telicent-ds/pull/24

332 storybook deploy

---

README.md

Created to get feedback from @procolecato for https://github.com/Telicent-io/telicent-ds/issues/332
(Note: I originally created https://github.com/telicent-oss/telicent-ds/pull/25 but accidentally merged it)

update(README.md): tweaks

---

package.json
src/components/TeliChip/TeliChip.tsx
src/components/TeliChip/telichip.css
src/components/TeliIcons/Icon.tsx
yarn.lock

The onDelete callback function is not being triggered in the Chip component. The fix was to [allow otherProps to be added to component base icon component](https://github.com/telicent-oss/telicent-ds/commit/17674f32edb73a74b47fdb6bd06b07086aa263fd)

Fix chip onDelete callback

---

package.json
src/v1/components/inputs/Button/Button.tsx
src/v1/components/inputs/Button/LinkButton.tsx
src/v1/components/inputs/Button/SecondaryButton.tsx
src/v1/theme/light-palette.ts
src/v1/theme/style-overrides/component-overrides/button-overrides.ts
src/v1/theme/style-overrides/component-overrides/index.ts
src/v1/theme/style-overrides/components.ts
src/v1/theme/theme.ts
vite.config.ts
yarn.lock

[TELFE-162](https://telicent.atlassian.net/browse/TELFE-162)
[TELFE-162]: https://telicent.atlassian.net/browse/TELFE-162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(Button): updates to button styles

---

.github/workflows/build-package.yml
.github/workflows/publish.yml

Moved build steps from publish.yml into build-package.yml. Cron job has been run every Monday at 9am against build-package.yml
Publish action now uses build workflow before publishing package
[telfe-73](https://telicent.atlassian.net/browse/TELFE-73)

chore: added cron schedule to build action

---

.github/workflows/build-package.yml

Changed default value from string to boolean

chore(build-package.yml): changed default value from string to bool

---

.github/workflows/build-package.yml

chore(build-package.yml): updated condition

---

src/contexts/OntologyStyles.tsx

Ticket: https://telicent.atlassian.net/browse/TELFE-529
Need to export the styles loading status; needed so that the node icon rather than text always appears if available when Graph is run from a node link, even on slow connections.
Styles loading status exported from the DS to be used by [Graph](https://github.com/Telicent-io/telicent-graph/pull/453).
- Existing test coverage:
Possible additional test coverage in https://telicent.atlassian.net/browse/TELFE-564.
Covered by QA in [Graph](https://github.com/Telicent-io/telicent-graph/pull/453).
---
<details>
---
- Generally, approve a PR if it makes the system better, even if it's not perfect. — [Google: The Standard of Code …

TELFE-529 Add loading styles

---

.github/workflows/upload-storybook.yml

Added deploy key - storybook books now publish
https://telicent-oss.github.io/telicent-ds/storybook-static/?path=/docs/design-system-ontology-styles--docs

update(upload-storybook.yml): perms

---

package.json
src/v1/components/data-display/AppSwitch/AppSwitch.test.tsx
src/v1/components/data-display/AppSwitch/AppSwitch.tsx
src/v1/components/layout/AppChrome.tsx
src/v1/components/surfaces/AppBar/AppBar.tsx
tsconfig.json
vite.config.ts

added v1 of app switch component to the app bar component.
related to [telfe-590](https://telicent.atlassian.net/browse/TELFE-590)

feat: app switch component

---

.gitignore
package.json
src/export.ts
src/schema/reactElementsSchema.ts
src/v1/components/data-display/Icons/CloseIcon.tsx
src/v1/components/surfaces/Card/Card.tsx
src/v1/components/utils/Modal/Modal.stories.tsx
src/v1/components/utils/Modal/Modal.test.tsx
src/v1/components/utils/Modal/Modal.tsx
src/v1/components/utils/Modal/schema.tsx
src/v1/components/utils/index.ts
yarn.lock

Ticket: https://telicent.atlassian.net/browse/TELFE-435
Add an opinionated Modal that exposes enough of its guts - that no one needs to stick their hands in
https://github.com/user-attachments/assets/a64168de-f66d-4814-b214-925cfd62a949
- Create modal with a bunch of props removed
- Demo usage in storybook for data catalog
- I left more comments than normal,I wanna make my decision process around design-system very clear (and open to criticism/feedback)
- The schema for the new Modal props is not good enough to use for schema-type-to-real-type comparisons
Pixel Perfection; In a bit of a rush.
---
<details>
---
- Generally, approve a PR if it makes the system better, even if it's not perfect. — [Google: The Standard of …

feat(v1 Modal): added

---

package.json
src/v1/components/utils/Modal/Modal.stories.tsx
src/v1/components/utils/Modal/Modal.test.tsx
src/v1/components/utils/Modal/Modal.tsx

Small tweaks based off chat with Alecs

fix: Tweak modal and version

---

src/v1/components/data-display/FontAwesomeIcons/DownloadIcon.tsx
src/v1/components/data-display/FontAwesomeIcons/index.ts

Ticket: https://telicent.atlassian.net/browse/TELFE-391
Provide relevant download icon for ticket above.
Font Awesome icon imported and exported.
- Existing tests.
- Ticket to cover DownloadIcon.tsx tests to follow:
- Download icon used differs slightly from [design](https://telicent.atlassian.net/browse/TELFE-391) due to availability of Font Awesome free icons.
- Download icon used in [this PR](https://github.com/Telicent-io/telicent-search/pull/610).

TELFE-391 Export search results as CSV

---

src/v1/components/data-display/AppSwitch/AppSwitch.tsx
src/v1/components/data-display/index.ts

Exporting app switch library schema

fix: export app switch library schema

---

src/v1/components/inputs/SearchBox/MiniSearchBox.stories.tsx
src/v1/components/inputs/SearchBox/MiniSearchBox.tsx
src/v1/components/surfaces/PopOver/PopOver.stories.tsx
src/v1/components/surfaces/PopOver/Popover.tsx

to support the work for ticket [telfe-279](https://telicent.atlassian.net/browse/TELFE-279)

feat: added minisearchbox and popover components

---

src/v1/components/inputs/SearchBox/MiniSearchBox.tsx
src/v1/components/inputs/SearchBox/index.ts
src/v1/components/inputs/index.ts

exporting minisearchbox component

fix: export minisearchbox component

---

src/v1/components/surfaces/FloatingPanel/__tests__/useFloatingPanels.test.tsx
src/v1/components/surfaces/FloatingPanel/index.ts
src/v1/components/surfaces/FloatingPanel/useFloatingPanels.ts

In the previous PR, I removed the custom hook which I thought wasn't needed but it still is. This PR adds is back with updates made to the hook

fix:(floating-panel): added usefloatingpanels hook

---

.github/workflows/upload-storybook.yml

fix(upload-storybook.yml): Details link

---

src/components/TeliSelect/TeliSelect.tsx

Extending props as part of https://telicent.atlassian.net/browse/TELFE-733 to address UI changes

fix: added renderValue prop

---

src/components/TeliSelect/TeliSelect.tsx

Forgot to use prop in the previous PR. renderValue is now passed to the Select component

fix: using renderValue prop

---

src/v1/components/surfaces/FixedPanel/FixedPanel.tsx
src/v1/components/surfaces/index.ts

@ACoolmanTelicent Trying a diiferent method to export, I don't know if you have had any experience with this way of doing things?

fix: try exporting as default rather than wildcard

---

src/components/SearchAutocomplete/SearchAutocomplete.tsx
yarn.lock

https://telicent.atlassian.net/browse/TELFE-446
add name property to autocomplete component
Linked DS to graph and manually checked the output.

fix: pass name through autocomplete

---

.github/workflows/publish.yml

Update deprecated github action

fix: actions/download-artifact@v4

---

src/v1/components/layout/FlexGrid.stories.tsx

A storybook I did a few months ago but never merged
FlexGrid
* [Basic Columns](https://telicent-oss.github.io/telicent-ds/story/flexgrid/?path=/story/layout-flexgrid--basic-columns)
* [Rows](https://telicent-oss.github.io/telicent-ds/story/flexgrid/?path=/story/layout-flexgrid--rows)
* [Main /  Detail Layout](https://telicent-oss.github.io/telicent-ds/story/flexgrid/?path=/story/layout-flexgrid--main-detail-layout)

feat(FlexGrid): stories

---

.github/workflows/build-package.yml
.github/workflows/publish-release-candidate.yml
.github/workflows/publish.yml
package.json
src/component-library/README.md
src/component-library/components/data-display/SocketedText.stories.tsx
src/component-library/components/data-display/SocketedText.test.tsx
src/component-library/components/data-display/SocketedText.tsx
src/export.ts
src/v1/components/data-display/Text/Text.test.tsx
src/v1/components/layout/FlexGrid.stories.tsx
src/v1/theme/ThemeViewer.stories.tsx
src/v1/theme/ThemeViewer.test.tsx
src/v1/theme/ThemeViewer.tsx
yarn.lock

Ticket: https://telicent.atlassian.net/browse/TELFE-958
Create component for text + icon
* [SocketedText](https://telicent-oss.github.io/telicent-ds/TELFE-958/SocketedText/?path=/docs/component-library-data-display-socketedtext--docs)
* [ThemeViewer](https://telicent-oss.github.io/telicent-ds/TELFE-958/SocketedText/?path=/docs/theme-themeviewer--docs) - makes it easier (but not easy) to explore the theme object
Not able to test - as can't link locally - but running out of time. So I'll just publish and test.
Once I'm happy with it, I'll write the unit tests.
---
<details>
---
- Generally, approve a PR if it makes the system better, even if it's not perfect. — [Google: The Standard of Code …

feat(component-library): [TELFE-958] SocketedText

---

src/v1/components/surfaces/AppBar/AppBar.stories.tsx
src/v1/components/surfaces/AppBar/AppBar.tsx
src/v1/theme/colors/admin-blue.ts
src/v1/theme/colors/theme-colors.ts

https://telicent.atlassian.net/browse/TELFE-813
Added a versionNumber prop.
Removed beta.
Renamed the UserProfile prop to action, as it can be used for more than just the user profile.
For example, in Access, we don't have a user profile but instead a sign-out button in the same place.
Added extra stories to reflect the new options.
Introduced the AdminBlue theme.

TELFE-813 - update on app bar

---

src/main.css
src/v1/components/surfaces/AppBar/AppBar.tsx
src/v1/theme/style-overrides/components.ts
src/v1/theme/theme.ts

Fixed an issue where the MUI AppBar wasn’t picking up the dark background colour correctly. Also removed the elevation overlay in dark mode, which was slightly altering the background colour.

fix: AppBar - background colour in dark mode

---

src/component-library/Map/FeatureMap.tsx

Noticed that the animation was laboriously slow so have added a max duration

fix: set max transition duration

---

src/v1/components/surfaces/AppBar/AppBar.test.tsx
src/v1/components/surfaces/AppBar/AppBar.tsx

Adding onClick to the AppBar. 
- currently needed for Search

feat: add on click function to AppBar

---

src/v1/components/surfaces/AppBar/AppBar.test.tsx
src/v1/components/surfaces/AppBar/AppBar.tsx

Had a quick call with Justin and fixed the design differences on the AppBar. 
Also added a toUpperCase to make sure the appName is always capitalised.

fix: updating styles to match desgin

---

src/v1/components/inputs/SearchBox/MiniSearchAutocomplete.tsx
src/v1/components/surfaces/FloatingPanel/FloatingPanelDockItem.tsx
src/v1/components/surfaces/FloatingPanel/__tests__/FloatingPanelDockItem.test.tsx

https://telicent.atlassian.net/browse/TELFE-848
- Fixed duplicate keys within autocomplete
- Removed close button from docked items
Removed now-redundant tests

Telfe 848/uplift fixes

---

src/v1/components/inputs/SearchBox/MiniSearchAutocomplete.test.tsx
src/v1/components/inputs/SearchBox/MiniSearchAutocomplete.tsx

https://telicent.atlassian.net/browse/TELFE-848
Added an onClick handler for list items
Added jest tests

fix: run on search when list item is selected

---

src/v1/components/data-display/AppSwitch/AppSwitch.stories.tsx
src/v1/components/surfaces/AppBar/AppBar.stories.tsx
src/v1/components/surfaces/AppBar/AppBar.tsx

https://telicent.atlassian.net/browse/TELFE-1093
Update app bar to make brand optional so we can use on Search home page.

feat: update app bar to make brand optional

---

.github/pull_request_template.md
.github/workflows/build-package.yml
.github/workflows/publish-release-candidate.yml
.github/workflows/publish.yml
.github/workflows/upload-storybook.yml
.husky/pre-commit
package.json
yarn.lock

- Add pull request template
- Gave me a chance to double-check the install process of `tefe`

feat(tefe): [TELFE-920] add

---

package.json
src/candidate-packages/utils-lib/src/GraphApp/constants.test.ts
src/candidate-packages/utils-lib/src/GraphApp/constants.ts
src/candidate-packages/utils-lib/src/index.ts
src/export.ts

Ticket: https://telicent.atlassian.net/browse/TELFE-1126
Add shared value for query param that allows Graph to load "nodes" with a query param
Added a contant
---
<details>
---
2. [Review the code](https://google.github.io/eng-practices/review/reviewer/looking-for.html)
3. Request any changes that are essential.
4. For non-essential comments: …

fix(utils-lib): [TELFE-1126] add GRAPH_APP.QUERY_PARAM.NODES

---

package.json
src/candidate-packages/authorize-flow/AuthModal.tsx
src/candidate-packages/authorize-flow/index.ts
src/candidate-packages/authorize-flow/types.ts
src/candidate-packages/authorize-flow/withSessionHandling.ts
src/export.ts
yarn.lock

Ticket: [TELFE-1096](https://telicent.atlassian.net/browse/TELFE-1096)
Add reusable auth logic.
- add api factory with interceptor to handle 401's and broadcast `unathorized` message on the specified channel.
- Create auth-modal that listens for `authorized` and `unauthorized` message events on the specified channel.
Linked DS to graph and carried out manual testing.
To use in other apps
```js
const bc = new BroadcastChannel('auth-events');
const apiFactory = createApi();
apiFactory.withSessionHandling({
broadcastChannel: bc,
keysToInvalidate: ['user'],
queryClient,
});
const api = apiFactory.build().instance;
```
---
<details>
---
- Generally, approve a PR if it makes the system better, even if it's not perfect. — …

feat: add auth modal

---

src/candidate-packages/authorize-flow/AuthModal.tsx
src/candidate-packages/authorize-flow/broadcastChannelService.ts
src/candidate-packages/authorize-flow/types.ts
src/setupTests.tsx

fix: handle strict mode

---

src/candidate-packages/authorize-flow/AuthModal.tsx

Add scrollbar to Auth modal
---
<details>
---
2. [Review the code](https://google.github.io/eng-practices/review/reviewer/looking-for.html)
3. Request any changes that are essential.
4. For non-essential comments:
- Use prefixes, e.g. "**nit:** change to Pascal case"
- **nit:** small, non-essential change
- **obs:** just an observation, …

fix: add scroll y to auth modal

---

src/candidate-packages/authorize-flow/AuthModal.tsx

Ticket: https://telicent.atlassian.net/browse/TELFE-644 
Add close button to the auth modal 
Updated the style of the button to be secondary
https://github.com/user-attachments/assets/7f1c0136-f82b-4cff-9e8b-39378d3b8ba0
---
<details>
---
2. [Review the code](https://google.github.io/eng-practices/review/reviewer/looking-for.html)
3. Request …

fix: add close button to auth modal

---

src/v1/components/inputs/Select/Select.stories.tsx
src/v1/components/inputs/Select/Select.tsx
src/v1/components/inputs/index.ts
src/v1/theme/createTheme.test.ts
src/v1/theme/style-overrides/components.ts

Ticket: https://telicent.atlassian.net/browse/TELFE-759
Add a new Select component to the DS that will replace the old TeliSelect. 
Added MenuItem styles to the components override, as it's used in multiple places. 
Added a better description to the story 
---
<details>
---
2. [Review the …

feat: add select dropdown

---

.husky/pre-push
package.json
src/candidate-packages/authorize-flow/types.ts
src/component-library/Map/FeatureMap.stories.tsx
src/component-library/Map/FeatureMap.tsx
src/component-library/Map/layer-selector/useLayerSelector.ts
src/components/TeliButton/TeliButton.tsx
src/components/TeliButton/TeliButtonBase.tsx
src/v1/components/data-display/DropdownButton/DropdownButton.test.tsx
src/v1/components/inputs/SearchBox/MiniSearchAutocomplete.stories.tsx
src/v1/components/inputs/SearchBox/MiniSearchAutocomplete.tsx
src/v1/theme/colors/theme-colors.ts

Ticket: https://telicent.atlassian.net/browse/TELFE-647
Fix TS errors - as refactoring was made difficult as hard to tell if I was introducing type errors or not.
- Everything touched - fixed types.
- FeatureMap - Did one change to make it accept vectorStyles as an array — not because I particularly want to support array — more to just fix the TS error
- Ran through storybook for Feature map - as this is the only thing that had changed
https://github.com/user-attachments/assets/6dad1f63-5d83-4f5d-9404-ddc8f47ac673
- Test in Graph and Search
https://github.com/user-attachments/assets/3590d614-d1c6-4033-b248-151b7685d185
https://github.com/user-attachments/assets/487bd14e-7cd1-4ac9-9dc2-1584b77bb01c
Doing anything in the ticket
---
<details>
<summary><strong>🕵️ Review …

fix(typescript): fix errors, re-enable checks

---

src/v1/components/inputs/index.ts

Quick fix, commented out the export statement and forgot to add it back.

fix: export textField

---

src/v1/components/data-display/UserProfile/UserProfile.tsx

Ticket: https://telicent.atlassian.net/browse/TELFE-1031
Removed border from user profile
- Pre-release version: _e.g. v1.2.3-JIRA-123.0_ 
<details>
<summary><strong>Design approval areas</strong></summary>
<hr />
A _indicative_ list of suggested screenshots or videos.
Action each: Mark "`[x]`" (click) for _complete_, or "`[-]`" for _not-applicable_.
</details>
---
<details>
---
- PR with …

fix: remove border around user profile modal
